#!/usr/bin/env bash

host=$1

get_info() {
	reply=$1
	info=$(
		echo "$reply" |
		grep -i "from" |
		sed "s/^.*[Ff]rom\ \(.*\)/\1/" |
		cut -d ' ' -f 1,2 |
		cut -d ':' -f 1 |
		sed 's/^\([0-9]\{1,3\}\(\.[0-9]\{1,3\}\)\{3\}\).*$/\1\ (\1)/'
	)
	if [ -n "$info" ]; then
		echo "$info"
	else
		echo "? (?)"
	fi
}

get_ip() {
	info=$1
	echo "$info" |
	sed 's/^.*\ (\(.*\))$/\1/'
}

get_hostname() {
	info=$1
	echo "$info" |
	sed 's/^\(.*\)\ (.*)$/\1/'
}

get_avg_ping() {
	reply=$1
	avg_ping=$(
		echo "$reply" |
		grep 'rtt' |
		cut -d '/' -f 5
	)
	if [ -z "$avg_ping" ]; then
		avg_ping="???"
	fi
	echo "$avg_ping"
}

for (( hop = 0; hop < 64; hop++ )); do 
	reply=`ping -c 1 -t $hop $host`

	if [ $? -eq 1 ]; then
		info=$(get_info "$reply")
		ip=$(get_ip "$info")

		if [ "$ip" = "?" ]; then
			avg_ping="?"
		else
			reply=`ping -c 1 -q $ip`
			avg_ping=$(get_avg_ping "$reply")
		fi
		
		echo "$hop - $info - $avg_ping ms"
	else
		info=$(get_info "$reply")
		ip=$(get_ip "$info")
		reply=`ping -c 1 $ip`
		avg_ping=$(get_avg_ping "$reply")
		echo "$hop - $info - $avg_ping ms"
		break
	fi
done

# vim: set ts=8 sw=8 tw=0 noet :
