#!/usr/bin/env bash

host=$1

get_info() {
	reply=$1
	info=$(
		echo "$reply" |
		grep -i "from" |
		sed "s/^.*[Ff]rom\ \(.*\)/\1/" |
		cut -d ' ' -f 1,2 |
		cut -d ':' -f 1 |
		sed 's/^\([0-9]\{1,3\}\(\.[0-9]\{1,3\}\)\{3\}\).*$/\1\ (\1)/'
	)
	if [ -n "$info" ]; then
		echo "$info"
	else
		echo "? (?)"
	fi
}

get_ip() {
	info=$1
	echo "$info" |
	sed 's/^.*\ (\(.*\))$/\1/'
}

get_hostname() {
	info=$1
	echo "$info" |
	sed 's/^\(.*\)\ (.*)$/\1/'
}

get_avg_ping() {
	reply=$1
	avg_ping=$(
		echo "$reply" |
		grep 'rtt' |
		cut -d '/' -f 5
	)
	if [ -z "$avg_ping" ]; then
		avg_ping="???"
	fi
	echo "$avg_ping"
}

add_to_buffer() {
	buffer=$1
	line=$2
	
	if [ -n "$buffer" ]; then
		echo -e "$buffer\r\n$line" |
		sort
	else
		echo -e "$line"
	fi
}

{
	last_hop=0
	for (( hop = 1; hop < 64; hop++ )); do 
		reply=$(ping -c 1 -t $hop $host)
		err=$?

		{
			info=$(get_info "$reply")
			ip=$(get_ip "$info")

			if [ "$ip" = "?" ]; then
				avg_ping="?"
			else
				reply=$(ping -c 1 -i 0.2 -q $ip)
				avg_ping=$(get_avg_ping "$reply")
			fi
				
			echo "$hop - $avg_ping ms - $info"
			last_hop=$hop
		}&

		[[ $err == 1 ]] || break
	done 
} | {
	last_hop=0
	while read line; do
		hop=$(echo $line | cut -d " " -f 1)
		if [ $(expr $hop - 1 == $last_hop) -eq 1 ]; then
			echo -e "$line"
			last_hop=$hop
		else
			buffer=$(add_to_buffer "$buffer" "$line")
		fi
		
		if [ -n "$buffer" ]; then
			buffer_head=$(echo -e "$buffer" | head -n 1)
			hop=$(echo "$buffer_head" | cut -d " " -f 1)

			if [ $(expr $hop - 1 == $last_hop) -eq 1 ]; then
				echo -e "$buffer_head"
				last_hop=$hop
				buffer=$(echo -e "$buffer" | tail -n +2)
			fi
		fi
	done
}

wait

# vim: set ts=8 sw=8 tw=0 noet :
